services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: jtoye-keycloak-host
    command: ["start-dev", "--import-realm", "--http-port=8081"]
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin123}
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    network_mode: host
